### ISSUE TITLE
Allow Users to Create Input, Output, and Select Tags Directly from the UI

### ISSUE THREAD

**Issue by Beazurt** [TBDFramework/TagSelectModule#2]
It'd be nice to configure everything from this page instead of configuring Tags first and this last.

**Comment by becega** [comment]
Would you want the ability to create tags from here? would they be based on the name of the select and the datatype? or how do you want to create them?

**Comment by Beazurt** [comment]
I think a common use-case for this module is adding the select module to an existing mapping pathway. In this case a user needs to create a new tag for one of the inputs, break the mapping from the Channel to the old Tag and map it to the new one. In some cases a user may not have created Tags for Input B or the Select yet either. It'd be nice if all of this could be corrected from this UI instead of having to bounce around to many.

![capture](https://cloud.githubusercontent.com/assets/8322360/13116582/0d8e7e6c-d562-11e5-8908-0c5db7cb104b.PNG)

In this diagram, a user at the very least would want to be able to create Tag A' and map the old channel to the new tag. It'd be great if this could be automated. They may also want to create and map Tag B and Select Tag by selecting a channel for an input instead of a Tag. This may be less common though as most I/O modules now create Tags for users automatically.

**Comment by Beazurt** [comment]
Technically the mapping arrows that are connected to the orange Tags in the above picture should also be orange. It'd be nice if those could also be scripted for a user.

**Comment by becega** [comment]
THe mapping columns now allow to create Tags. I didnt add a mass create option but should give what we need with the latest version of Table API @Beazurt
