### ISSUE TITLE
Scripting the VI Includes Calls This Module an 'Alarm Module'

### ISSUE THREAD

**Issue by Beazurt** [TBDFramework/TagSelectModule#3]
This doesn't affect execution (it still runs as the Tag Select), but its really confusing when you look in the Includes VI and see this class named Alarms.

**Comment by becega** [comment]
Yes not sure where its getting the alarms module or exactly where to change it. If you right click on the node and select use long name it will use tag select module.
I created the module using the alarms as a starting point.

**Comment by Beazurt** [comment]
I think you change it in the runtime class properties under Documentation in the 'Localized Name' field

**Comment by becega** [comment]
Yes it was that property but It was the one in configuration class

**Comment by Beazurt** [comment]
The runtime class was misnamed in that property also. Did you change that one as well? We drop the runtime class in the VI includes, not the config.

**Comment by becega** [comment]
Yes updated both of them
