### ISSUE TITLE
Refresh UI Event - put in parent?

### ISSUE THREAD

**Issue by pollockm** [TBDFramework/TagSelectModule#5]
The Refresh UI Event function is not a part of the tag select class, and it looks like it would be a useful API function to have elsewhere (we'll probably need to have something precisely like it for the new module template that uses the table API).  Should this be implemented in the table API or at the CEF level?

**Comment by becega** [comment]
Some of this have been moved to the table API and some of it is implemented at editor module parent to allow refresh
