### ISSUE TITLE
Changing the data type is hard

### ISSUE THREAD

**Issue by theSloopJohnB** [TBDFramework/TagSelectModule#9]
You need to double click, and then wait a few seconds, and then sometimes you can then edit the datatype. Double clicking doesn't work every time.

**Comment by theSloopJohnB** [comment]
Once this is fixed, we will need to update the forum documentation (that I'm writing right now).

**Comment by knoxberry** [comment]
I think this may be the same issue I'm seeing. I wasn't able to change the data type at all. Editing the configuration editor and moving the data type enum to the front of the front panel solved the issue for me. Maybe the table manager should move the data type enum in front of the table automatically.

**Comment by becega** [comment]
I think the main issue is that the enum is not in front of the table, moving it to the front appears to solve the issue.
